# Generated by Django 4.2.5 on 2023-09-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('birthday', models.DateTimeField()),
            ],
        ),
    ]
